---
- hosts: all
  tasks:
  - name: "Install required software"
    apt:
      name: "{{ packages }}"
      state: present
    become: true
    vars:
      packages:
      - git
      - docker
      - docker-compose
      - python3-pip
  - name: "Starting Docker"
    become: true
    service:
      name: docker
      state: started
      enabled: yes  